
name: Build app 

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: fleet-management
        postgresql password: postgres
    
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
